### ISSUE TITLE
GNOME Screenshot has wrong icon in the application

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#56] opened 2019-04-10 13:05 UTC
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 iso19 

**Related Application and/or Shell theming (or name of widget)**
GNOME Screenshot

**Actual issue**
The icon in the top left of GNOME Screenshot seems to be scaled improperly and the wrong icon. In Ubuntu, the icon used in the top left is a smaller version of the one in the middle of the app.
![screenshot1](https://user-images.githubusercontent.com/7460774/55880506-104c4c80-5b5e-11e9-9dd9-3e30d876f837.png)

**Behavior in Ubuntu**
![screenshotubuntu](https://user-images.githubusercontent.com/7460774/55880898-e0ea0f80-5b5e-11e9-8694-47495a93abf6.png)

**Comment by jackpot51** [comment] 2019-04-10 15:04
Duplicate of https://github.com/pop-os/icon-theme/issues/58

**Closed by jackpot51** 2019-04-10 15:04 UTC
Labels: v2
