### ISSUE TITLE
Terminal icon is different in favorites bar than in activities menu

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#54] opened 2019-04-09 17:08 UTC
**Reporter info**

 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
19.04 ISO19

**Related Application and/or Shell theming (or name of widget)**
GNOME terminal

**Actual issue**
The GNOME terminal icon that is on the favorites bar is different than the one shown in the full activities list. My concern here is the potential confusion from users due to the inconsistency.

![Screenshot from 2019-04-09 09-39-31](https://user-images.githubusercontent.com/7460774/55820185-bd1fbe80-5ab7-11e9-89bc-c8b71bff710a.png)

**Comment by jackpot51** [comment] 2019-04-10 15:04
Duplicate of https://github.com/pop-os/icon-theme/issues/58

**Closed by jackpot51** 2019-04-10 15:04 UTC
Labels: v2
