### ISSUE TITLE
Calculator icon is missing multiplication symbol

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#53] opened 2019-04-09 16:53 UTC
* Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

Pop!_OS 19.04 iso19

The calculator icon seems to be missing the multiplication sign:

![calculator](https://user-images.githubusercontent.com/7460774/55819260-a5473b00-5ab5-11e9-8990-e32afa2610ac.png)

as seen in the application overview:

![Screenshot from 2019-04-09 09-39-31](https://user-images.githubusercontent.com/7460774/55818491-f8b88980-5ab3-11e9-953c-46901ab2ea52.png)

**Comment by jackpot51** [comment] 2019-04-10 15:04
Duplicate of https://github.com/pop-os/icon-theme/issues/58

**Closed by jackpot51** 2019-04-10 15:04 UTC
Labels: v2
