### ISSUE TITLE
19.04: About page shows Ubuntu icon

### ISSUE THREAD

**Issue by jackpot51** [pop-os/icon-theme#52] opened 2019-04-09 16:52 UTC
![Screenshot from 2019-04-09 10-51-04](https://user-images.githubusercontent.com/7741236/55819210-7e890480-5ab5-11e9-8cb4-976caddfeb2c.png)

**Comment by brs17** [comment] 2019-04-09 16:59
Duplicate of https://github.com/pop-os/icon-theme/issues/50

**Closed by brs17** 2019-04-09 16:59 UTC
Labels: bug, high priority, v2
