### ISSUE TITLE
Gnome-control-center displays wrong icon theme

### ISSUE THREAD

**Issue by brs17** [pop-os/icon-theme#59] opened 2019-04-10 14:08 UTC
**Reporter info**

 * Distribution - (run ```lsb_release -a```) Pop!_OS 19.04
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```) 3.24.7-1ubuntu1
 * Desktop environment - GNOME

**Pop version (if you knew)**
Pop!_OS 19.04 iso19 

**Related Application and/or Shell theming (or name of widget)**
gnome-control-center

**Actual issue**
Throughout gnome-control-center, there are numerous locations where application icon themes are present. In all of these locations, the icons are not themed properly.

Locations in gnome-control-center where icons are not themed properly:
- Notifications tab
- Search tab
- Applications tab
- Default Applications tab

**Comment by jackpot51** [comment] 2019-04-10 15:03
Duplicate of https://github.com/pop-os/icon-theme/issues/58

**Closed by jackpot51** 2019-04-10 15:03 UTC
Labels: v2
